//! Generated `index.md` renderer — mirrors Python's `touchstone/render.py`.
//!
//! T1 (rebuild drill) demands byte-identical regeneration. This must match
//! Python's output exactly, including the okf_version frontmatter on the root
//! index, section ordering, per-type grouping, and the flag suffixes.

use crate::parse::RichConcept;

const BANNER: &str = "<!-- generated by `touchstone index` -- do not edit -->";
const OKF_VERSION: &str = "0.2";

fn title_for_dir(rel: &str) -> String {
    if rel.is_empty() || rel == "." {
        return "Bundle".to_string();
    }
    let name = rel.trim_end_matches('/').rsplit('/').next().unwrap_or(rel);
    title_case(&name.replace('-', " ").replace('_', " "))
}

fn title_case(s: &str) -> String {
    s.split_whitespace()
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

/// Render one directory's `index.md` content.
///
/// `rel_dir` — bundle-relative directory path (empty string = bundle root).
/// `concepts` — concepts whose direct parent is `rel_dir`.
/// `subdirs` — `(child_dir_name, count)` pairs for sub-directories.
/// `is_root` — true only for the bundle root index.
pub fn render_index(
    rel_dir: &str,
    concepts: &[&RichConcept],
    subdirs: &[(String, usize)],
    is_root: bool,
) -> String {
    let mut parts: Vec<String> = Vec::new();

    if is_root {
        parts.push(format!("---\nokf_version: \"{OKF_VERSION}\"\n---\n"));
    }
    parts.push(format!("{BANNER}\n"));
    parts.push(format!("# {}\n", title_for_dir(rel_dir)));

    if !subdirs.is_empty() {
        parts.push("\n## Sections\n\n".to_string());
        let mut sorted_subdirs: Vec<&(String, usize)> = subdirs.iter().collect();
        sorted_subdirs.sort_by(|a, b| a.0.cmp(&b.0));
        for (name, n) in sorted_subdirs {
            let label = title_case(&name.replace('-', " ").replace('_', " "));
            let noun = if *n == 1 { "concept" } else { "concepts" };
            parts.push(format!("* [{label}]({name}/index.md) - {n} {noun}\n"));
        }
    }

    if !concepts.is_empty() {
        // Group by type
        let mut by_type: std::collections::BTreeMap<String, Vec<&RichConcept>> =
            std::collections::BTreeMap::new();
        for c in concepts {
            let t = if c.concept_type().is_empty() {
                "Untyped".to_string()
            } else {
                c.concept_type().to_string()
            };
            by_type.entry(t).or_default().push(c);
        }

        for (typ, mut cs) in by_type {
            parts.push(format!("\n## {typ}\n\n"));
            cs.sort_by(|a, b| {
                a.title()
                    .to_lowercase()
                    .cmp(&b.title().to_lowercase())
                    .then(a.path.cmp(&b.path))
            });
            for c in cs {
                // Bundle-relative URL from this directory
                let url = if rel_dir.is_empty() {
                    c.path.clone()
                } else {
                    relpath(&c.path, rel_dir)
                };
                let desc = c.description().trim().replace('\n', " ");
                let mut flags: Vec<&str> = Vec::new();
                if c.status() == "draft" {
                    flags.push("draft");
                }
                if c.status() == "deprecated" {
                    flags.push("deprecated");
                }
                if c.trust() == "human" {
                    flags.push("verified");
                }
                let suffix = if flags.is_empty() {
                    String::new()
                } else {
                    format!(" _({})_", flags.join(", "))
                };
                let mut line = format!("* [{}]({url})", c.title());
                if !desc.is_empty() {
                    line.push_str(&format!(" - {desc}"));
                }
                parts.push(line + &suffix + "\n");
            }
        }
    }

    if concepts.is_empty() && subdirs.is_empty() {
        parts.push("\n_No concepts yet._\n".to_string());
    }

    parts.join("")
}

/// Compute a POSIX relative path from `from_dir` to `path`.
/// Both are bundle-relative. Mirrors Python's `posixpath.relpath(c.path, rel_dir)`.
fn relpath(path: &str, from_dir: &str) -> String {
    let path_parts: Vec<&str> = path.split('/').collect();
    let dir_parts: Vec<&str> = if from_dir.is_empty() {
        vec![]
    } else {
        from_dir.split('/').collect()
    };

    // Find common prefix
    let common = path_parts
        .iter()
        .zip(dir_parts.iter())
        .take_while(|(a, b)| a == b)
        .count();

    let up = dir_parts.len() - common;
    let mut result: Vec<&str> = std::iter::repeat("..").take(up).collect();
    result.extend_from_slice(&path_parts[common..]);
    if result.is_empty() {
        ".".to_string()
    } else {
        result.join("/")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn title_for_dir_root() {
        assert_eq!(title_for_dir(""), "Bundle");
    }

    #[test]
    fn title_for_dir_subdir() {
        assert_eq!(title_for_dir("decisions"), "Decisions");
        assert_eq!(title_for_dir("my-notes"), "My Notes");
    }

    #[test]
    fn relpath_sibling() {
        assert_eq!(relpath("notes/foo.md", "notes"), "foo.md");
    }

    #[test]
    fn relpath_from_root() {
        assert_eq!(relpath("notes/foo.md", ""), "notes/foo.md");
    }

    #[test]
    fn relpath_parent() {
        assert_eq!(relpath("foo.md", "notes"), "../foo.md");
    }

    #[test]
    fn render_empty_dir() {
        let out = render_index("empty", &[], &[], false);
        assert!(out.contains("_No concepts yet._"));
    }

    #[test]
    fn render_root_has_okf_version() {
        let out = render_index("", &[], &[], true);
        assert!(out.contains("okf_version"));
    }

    #[test]
    fn render_banner_present() {
        let out = render_index("", &[], &[], false);
        assert!(out.contains(BANNER));
    }
}
