"""Generated `index.md` -- the human index (ARCHITECTURE.md §5).

Committed, so the bundle browses correctly on GitHub and in Obsidian with zero
tooling. Generated, so it is never hand-maintained. Deterministic, because T1
(the rebuild drill) demands byte-identical regeneration.
"""
from __future__ import annotations

import posixpath

from .okf import OKF_VERSION, Concept

BANNER = "<!-- generated by `touchstone index` -- do not edit -->"


def _title_for_dir(rel: str) -> str:
    if rel in ("", "."):
        return "Bundle"
    name = rel.rstrip("/").rsplit("/", 1)[-1]
    return name.replace("-", " ").replace("_", " ").title()


def render_index(rel_dir: str, concepts: list[Concept], subdirs: list[tuple[str, int]],
                 *, is_root: bool) -> str:
    """`* [Title](relative-url) - description`, per the spec's prescribed shape."""
    parts: list[str] = []
    if is_root:
        # spec: okf_version is declared in the ROOT index.md frontmatter only
        parts.append(f"---\nokf_version: \"{OKF_VERSION}\"\n---\n")
    parts.append(f"{BANNER}\n")
    parts.append(f"# {_title_for_dir(rel_dir)}\n")

    if subdirs:
        parts.append("\n## Sections\n\n")
        for name, n in sorted(subdirs):
            label = name.replace("-", " ").replace("_", " ").title()
            noun = "concept" if n == 1 else "concepts"
            parts.append(f"* [{label}]({name}/index.md) - {n} {noun}\n")

    if concepts:
        by_type: dict[str, list[Concept]] = {}
        for c in concepts:
            by_type.setdefault(c.type or "Untyped", []).append(c)
        for typ in sorted(by_type):
            parts.append(f"\n## {typ}\n\n")
            for c in sorted(by_type[typ], key=lambda x: (x.title.lower(), x.path)):
                url = posixpath.relpath(c.path, rel_dir) if rel_dir else c.path
                desc = c.description.strip().replace("\n", " ")
                flags = []
                if c.status == "draft":
                    flags.append("draft")
                if c.status == "deprecated":
                    flags.append("deprecated")
                if c.trust == "human":
                    flags.append("verified")
                suffix = f" _({', '.join(flags)})_" if flags else ""
                line = f"* [{c.title}]({url})"
                if desc:
                    line += f" - {desc}"
                parts.append(line + suffix + "\n")

    if not concepts and not subdirs:
        parts.append("\n_No concepts yet._\n")
    return "".join(parts)
