//! Secondary adapter — ConceptRepository port backed by filesystem walk.
//!
//! Imports `touchstone-ports` ONLY (hex ADR-001 / ARCHITECTURE.md rule 4).
//! std only: no external crates.
//!
//! Walk rules (from Python oracle `touchstone/cli.py:iter_concept_files`, with the
//! E4a correction):
//!   - Descend into directories, skipping those whose name starts with `.` or `_`,
//!     and `node_modules`.
//!   - Accept only `.md` files.
//!   - Skip `index.md` — it is generated by `touchstone index` (ARCHITECTURE.md).
//!   - DO NOT skip `log.md` — it is a legitimate concept (FINDINGS.md E4a). The
//!     Python prototype's `RESERVED = {"index.md", "log.md"}` is the documented bug;
//!     acme_retail/log.md is `type: Log` and must be indexed.
use touchstone_ports::{Concept, ConceptRepository};
use std::fs;
use std::path::{Path, PathBuf};

pub struct FsBundle {
    pub root: PathBuf,
}

impl FsBundle {
    pub fn new(root: impl Into<PathBuf>) -> Self {
        FsBundle { root: root.into() }
    }
}

impl ConceptRepository for FsBundle {
    fn list(&self) -> Vec<Concept> {
        let mut concepts = Vec::new();
        walk(&self.root, &self.root, &mut concepts);
        concepts.sort_by(|a, b| a.path.cmp(&b.path));
        concepts
    }
}

fn walk(root: &Path, dir: &Path, out: &mut Vec<Concept>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };

    let mut entries: Vec<_> = entries.flatten().collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let path = entry.path();
        let name = entry.file_name();
        let name = name.to_string_lossy();

        if path.is_dir() {
            if skip_dir(&name) {
                continue;
            }
            walk(root, &path, out);
        } else if path.is_file() {
            if !name.ends_with(".md") || name == "index.md" {
                continue;
            }
            let rel = path
                .strip_prefix(root)
                .expect("path must be under root")
                .to_slash_lossy();
            let raw = match fs::read(&path) {
                Ok(b) => b,
                Err(_) => continue,
            };
            let (concept_type, title) = extract_type_and_title(&raw);
            out.push(Concept { path: rel, concept_type, title });
        }
    }
}

fn skip_dir(name: &str) -> bool {
    name.starts_with('.') || name.starts_with('_') || name == "node_modules"
}

/// Extract `type` and `title` from OKF frontmatter using minimal line scanning.
///
/// Raw bytes are authoritative — this extracts string values without any type
/// coercion. Values are trimmed and stripped of one layer of surrounding `"` or `'`
/// when the entire value is quoted (handles the `title: "Quoted: with a colon"` case
/// from the adversarial fixture).
///
/// If no frontmatter block is found, or `type` is absent or empty, both fields
/// return empty strings. The caller receives the path regardless, so the concept is
/// still enumerated — conformance checking belongs to a higher layer.
fn extract_type_and_title(raw: &[u8]) -> (String, String) {
    let text = match std::str::from_utf8(raw) {
        Ok(s) => s,
        Err(_) => return (String::new(), String::new()),
    };
    // Normalise CRLF so delimiter matching works on all line endings.
    let norm = text.replace("\r\n", "\n").replace('\r', "\n");
    let norm = norm.trim_start_matches('\u{FEFF}'); // strip UTF-8 BOM if present

    if !norm.starts_with("---") {
        return (String::new(), String::new());
    }
    // Skip the opening `---` line.
    let rest = match norm.strip_prefix("---\n") {
        Some(s) => s,
        None => return (String::new(), String::new()),
    };

    let mut concept_type = String::new();
    let mut title = String::new();

    for line in rest.lines() {
        if line.trim() == "---" {
            break; // closing delimiter — done
        }
        if concept_type.is_empty() {
            if let Some(val) = scalar_after(line, "type") {
                concept_type = val;
            }
        }
        if title.is_empty() {
            if let Some(val) = scalar_after(line, "title") {
                title = val;
            }
        }
        if !concept_type.is_empty() && !title.is_empty() {
            break;
        }
    }

    (concept_type, title)
}

/// Return the trimmed scalar value for `key: <value>` on a frontmatter line,
/// or `None` if the line does not start with `<key>:`.
fn scalar_after(line: &str, key: &str) -> Option<String> {
    let prefix = format!("{key}:");
    let rest = line.strip_prefix(&prefix)?;
    let val = rest.trim();
    if val.is_empty() {
        return None;
    }
    Some(strip_quotes(val).to_string())
}

/// Strip one layer of matching `"..."` or `'...'` from a YAML plain scalar.
/// Only strips when the entire value is wrapped in matching quotes.
fn strip_quotes(s: &str) -> &str {
    if s.len() >= 2
        && ((s.starts_with('"') && s.ends_with('"'))
            || (s.starts_with('\'') && s.ends_with('\'')))
    {
        return &s[1..s.len() - 1];
    }
    s
}

/// Convert a Path to a forward-slash string (bundle-relative path).
trait ToSlashLossy {
    fn to_slash_lossy(&self) -> String;
}
impl ToSlashLossy for Path {
    fn to_slash_lossy(&self) -> String {
        #[cfg(windows)]
        {
            self.to_string_lossy().replace('\\', "/")
        }
        #[cfg(not(windows))]
        {
            self.to_string_lossy().into_owned()
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use touchstone_ports::ConceptRepository;

    // ── scalar extraction unit tests ──────────────────────────────────────────

    #[test]
    fn scalar_plain_value() {
        let (t, ttl) = extract_type_and_title(b"---\ntype: Note\ntitle: Hello\n---\n");
        assert_eq!(t, "Note");
        assert_eq!(ttl, "Hello");
    }

    #[test]
    fn scalar_multiword_type() {
        let (t, _) = extract_type_and_title(b"---\ntype: BigQuery Table\n---\n");
        assert_eq!(t, "BigQuery Table");
    }

    #[test]
    fn scalar_double_quoted_title() {
        // Adversarial fixture: `title: "Quoted: with a colon"`
        let (_, ttl) =
            extract_type_and_title(b"---\ntype: Note\ntitle: \"Quoted: with a colon\"\n---\n");
        assert_eq!(ttl, "Quoted: with a colon");
    }

    #[test]
    fn scalar_unicode_title() {
        let raw = "---\ntype: Note\ntitle: Unicode — em dash, café, 日本語\n---\n";
        let (t, ttl) = extract_type_and_title(raw.as_bytes());
        assert_eq!(t, "Note");
        assert_eq!(ttl, "Unicode — em dash, café, 日本語");
    }

    #[test]
    fn scalar_no_frontmatter_returns_empty() {
        let (t, ttl) = extract_type_and_title(b"Just a markdown file.\n");
        assert_eq!(t, "");
        assert_eq!(ttl, "");
    }

    #[test]
    fn scalar_missing_type_returns_empty() {
        let (t, _) = extract_type_and_title(b"---\ntitle: No type\n---\n");
        assert_eq!(t, "");
    }

    #[test]
    fn scalar_crlf_handled() {
        let raw = "---\r\ntype: Note\r\ntitle: CRLF\r\n---\r\n";
        let (t, ttl) = extract_type_and_title(raw.as_bytes());
        assert_eq!(t, "Note");
        assert_eq!(ttl, "CRLF");
    }

    // ── walk unit tests ───────────────────────────────────────────────────────

    #[test]
    fn walk_skips_index_md() {
        // _upstream/acme_retail has index.md at the root and in every subdir.
        let root = Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../../_upstream/acme_retail"
        ));
        let repo = FsBundle::new(root);
        let concepts = repo.list();
        assert!(
            concepts.iter().all(|c| !c.path.ends_with("index.md")),
            "index.md must be excluded from results"
        );
    }

    #[test]
    fn walk_skips_non_markdown_files() {
        // acme_retail/viz.html must not appear.
        let root = Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../../_upstream/acme_retail"
        ));
        let repo = FsBundle::new(root);
        let concepts = repo.list();
        assert!(
            concepts.iter().all(|c| c.path.ends_with(".md")),
            "only .md files must be returned"
        );
    }

    // ── CRITICAL: E4a — log.md is a legitimate concept ────────────────────────
    //
    // The Python prototype's `RESERVED = {"index.md", "log.md"}` silently drops
    // acme_retail/log.md (`type: Log`), indexing 9 of 10 concepts.
    // FINDINGS.md E4a records this as a real defect that the Rust adapter must NOT
    // reproduce. This test is the required gate case.

    #[test]
    fn acme_retail_returns_all_10_concepts() {
        let root = Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../../_upstream/acme_retail"
        ));
        let repo = FsBundle::new(root);
        let concepts = repo.list();

        assert_eq!(
            concepts.len(),
            10,
            "acme_retail must yield exactly 10 concepts (9 would mean log.md was wrongly skipped)"
        );
    }

    #[test]
    fn acme_retail_includes_log_md() {
        let root = Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../../_upstream/acme_retail"
        ));
        let repo = FsBundle::new(root);
        let concepts = repo.list();

        let log = concepts.iter().find(|c| c.path == "log.md");
        assert!(
            log.is_some(),
            "log.md must be indexed — it is `type: Log`, not a reserved name"
        );
        let log = log.unwrap();
        assert_eq!(log.concept_type, "Log");
        assert_eq!(log.title, "Acme Retail bundle history");
    }

    #[test]
    fn acme_retail_all_paths_are_correct() {
        let root = Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../../_upstream/acme_retail"
        ));
        let repo = FsBundle::new(root);
        let mut paths: Vec<_> = repo.list().into_iter().map(|c| c.path).collect();
        paths.sort();

        let mut expected: Vec<String> = vec![
            "computations/gross-margin-period.md",
            "computations/revenue-ytd.md",
            "log.md",
            "metrics/gross-margin-legacy.md",
            "metrics/gross-margin.md",
            "metrics/revenue.md",
            "policies/margin-standard.md",
            "policies/revenue-recognition.md",
            "skills/run-on-bq.md",
            "tables/orders.md",
        ]
        .into_iter()
        .map(String::from)
        .collect();
        expected.sort();

        assert_eq!(paths, expected);
    }

    #[test]
    fn acme_retail_concept_types_parsed() {
        let root = Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../../_upstream/acme_retail"
        ));
        let repo = FsBundle::new(root);
        let concepts = repo.list();

        let find = |path: &str| {
            concepts
                .iter()
                .find(|c| c.path == path)
                .map(|c| c.concept_type.as_str())
        };

        assert_eq!(find("metrics/revenue.md"), Some("Metric"));
        assert_eq!(find("tables/orders.md"), Some("BigQuery Table"));
        assert_eq!(find("skills/run-on-bq.md"), Some("Skill"));
        assert_eq!(find("log.md"), Some("Log"));
    }

    #[test]
    fn results_are_sorted_by_path() {
        let root = Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../../_upstream/acme_retail"
        ));
        let repo = FsBundle::new(root);
        let concepts = repo.list();
        let paths: Vec<_> = concepts.iter().map(|c| c.path.as_str()).collect();
        let mut sorted = paths.clone();
        sorted.sort();
        assert_eq!(paths, sorted, "list() must return concepts sorted by path");
    }
}
