//! Generated `index.md` renderer.
//!
//! This lives in the domain rather than in a primary adapter for one reason: T1 demands that
//! `index.md` regenerate **byte-identically**, and a renderer owned by the CLI would mean the
//! MCP surface either produced different bytes or produced none at all. Either way the two
//! adapters would only be at parity in name. One renderer, called by the use case, is what
//! makes "same use case, two skins" true rather than aspirational.

use crate::text::relative_path;
use crate::{ParsedConcept, Trust};
use std::collections::BTreeMap;

const BANNER: &str = "<!-- generated by `touchstone index` -- do not edit -->";
const OKF_VERSION: &str = "0.2";

fn title_case(s: &str) -> String {
    s.split_whitespace()
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn title_for_dir(rel: &str) -> String {
    if rel.is_empty() || rel == "." {
        return "Bundle".to_string();
    }
    let name = rel.trim_end_matches('/').rsplit('/').next().unwrap_or(rel);
    title_case(&name.replace('-', " ").replace('_', " "))
}

/// Render one directory's `index.md` content.
///
/// `rel_dir`  — bundle-relative directory path (empty string = bundle root).
/// `concepts` — concepts whose direct parent is `rel_dir`.
/// `subdirs`  — `(child_dir_name, count)` pairs.
/// `is_root`  — true only for the bundle root index.
pub fn render_index(
    rel_dir: &str,
    concepts: &[&ParsedConcept],
    subdirs: &[(String, usize)],
    is_root: bool,
) -> String {
    let mut parts: Vec<String> = Vec::new();

    if is_root {
        parts.push(format!("---\nokf_version: \"{OKF_VERSION}\"\n---\n"));
    }
    parts.push(format!("{BANNER}\n"));
    parts.push(format!("# {}\n", title_for_dir(rel_dir)));

    if !subdirs.is_empty() {
        parts.push("\n## Sections\n\n".to_string());
        let mut sorted: Vec<&(String, usize)> = subdirs.iter().collect();
        sorted.sort_by(|a, b| a.0.cmp(&b.0));
        for (name, n) in sorted {
            let label = title_case(&name.replace('-', " ").replace('_', " "));
            let noun = if *n == 1 { "concept" } else { "concepts" };
            parts.push(format!("* [{label}]({name}/index.md) - {n} {noun}\n"));
        }
    }

    if !concepts.is_empty() {
        let mut by_type: BTreeMap<String, Vec<&ParsedConcept>> = BTreeMap::new();
        for c in concepts {
            let t = if c.concept_type.is_empty() {
                "Untyped".to_string()
            } else {
                c.concept_type.clone()
            };
            by_type.entry(t).or_default().push(c);
        }

        for (typ, mut cs) in by_type {
            parts.push(format!("\n## {typ}\n\n"));
            cs.sort_by(|a, b| {
                a.title
                    .to_lowercase()
                    .cmp(&b.title.to_lowercase())
                    .then(a.path.cmp(&b.path))
            });
            for c in cs {
                let url = if rel_dir.is_empty() {
                    c.path.clone()
                } else {
                    relative_path(&c.path, rel_dir)
                };
                let desc = c.description.trim().replace('\n', " ");
                let mut flags: Vec<&str> = Vec::new();
                if c.status == "draft" {
                    flags.push("draft");
                }
                if c.status == "deprecated" {
                    flags.push("deprecated");
                }
                if c.trust == Trust::Verified {
                    flags.push("verified");
                }
                let suffix = if flags.is_empty() {
                    String::new()
                } else {
                    format!(" _({})_", flags.join(", "))
                };
                let mut line = format!("* [{}]({url})", c.title);
                if !desc.is_empty() {
                    line.push_str(&format!(" - {desc}"));
                }
                parts.push(line + &suffix + "\n");
            }
        }
    }

    if concepts.is_empty() && subdirs.is_empty() {
        parts.push("\n_No concepts yet._\n".to_string());
    }

    parts.join("")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn concept(path: &str, typ: &str, title: &str) -> ParsedConcept {
        ParsedConcept {
            path: path.to_string(),
            concept_type: typ.to_string(),
            title: title.to_string(),
            status: "stable".to_string(),
            ..Default::default()
        }
    }

    #[test]
    fn dir_titles_are_humanised() {
        assert_eq!(title_for_dir(""), "Bundle");
        assert_eq!(title_for_dir("decisions"), "Decisions");
        assert_eq!(title_for_dir("my-notes"), "My Notes");
    }

    #[test]
    fn empty_dir_says_so() {
        assert!(render_index("empty", &[], &[], false).contains("_No concepts yet._"));
    }

    #[test]
    fn only_the_root_index_carries_okf_version() {
        assert!(render_index("", &[], &[], true).contains("okf_version"));
        assert!(!render_index("sub", &[], &[], false).contains("okf_version"));
    }

    #[test]
    fn banner_is_always_present() {
        assert!(render_index("", &[], &[], false).contains(BANNER));
    }

    /// Byte-identical rebuild (T1) is only possible if ordering is total. Grouping is by type
    /// and then by lowercased title, with the path as the tie-break — without that last term
    /// two same-titled concepts could swap places between runs.
    #[test]
    fn ordering_is_total_and_deterministic() {
        let a = concept("n/b.md", "Note", "same");
        let b = concept("n/a.md", "Note", "Same");
        let once = render_index("n", &[&a, &b], &[], false);
        let twice = render_index("n", &[&b, &a], &[], false);
        assert_eq!(once, twice, "render must not depend on input order");
        assert!(
            once.find("a.md").unwrap() < once.find("b.md").unwrap(),
            "equal titles must tie-break on path"
        );
    }

    #[test]
    fn trust_and_status_become_flags() {
        let mut c = concept("n/a.md", "Note", "A");
        c.trust = Trust::Verified;
        assert!(render_index("n", &[&c], &[], false).contains("_(verified)_"));
        c.status = "draft".to_string();
        assert!(render_index("n", &[&c], &[], false).contains("_(draft, verified)_"));
    }
}
